name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # arch: [ia32, x64, arm64]
        arch: [x64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21.7.3
        architecture: ${{ matrix.arch }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: 缓存 Chocolatey 安装包
      id: cache-choco
      uses: actions/cache@v4
      with:
        path: |
          C:\ProgramData\chocolatey\lib
          C:\ProgramData\chocolatey\config
        key: ${{ runner.os }}-choco-${{ hashFiles('**/choco-packages.txt') }}  # 通过文件哈希控制缓存版本
  

    - name: Install Windows build tools
      run: |
        choco install -y python visualstudio2022-workload-vctools
        choco install -y windows-sdk-10.0
        # 生成版本锁定文件（示例）
        Get-Date > choco-packages.txt
    
    - name: Install Package Management
      run: |
        corepack enable
        corepack use pnpm@9.14.4

    - name: Install dependencies
      run: pnpm install
      
    - name: Build for ${{ matrix.arch }}
      run: |
        pnpm prebuild:cpp
        pnpm run build:cpp_${{ matrix.arch }}
      
    - name: Build TypeScript
      run: pnpm run build:ts
      
    # - name: Run tests
    #   run: pnpm test

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      